title: Abhee Jani's Webpage
author: Abhee Jani
email: abheejani@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my resume webpage. I hope you learn a little something about me from this page

# social links
github_username: abheejani
instagram_username: abheejani
gmail_username: abhejani

show_excerpts: true # set to false to remove excerpts on the homepage
